### ISSUE TITLE
The redux example throw an example when starting

### ISSUE THREAD

**Issue by radjivF** [paularmstrong/normalizr#347]
# Problem

the example from the redux files is not booting up 

**How**
I did ```npm install``` and run ```npm run start``` 
**Output**

```
/Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "/Users/radjivcarrere/Downloads/normalizr-master/.babelrc.js" at 0, attempted to resolve relative to "/Users/radjivcarrere/Downloads/normalizr-master" (While processing preset: "/Users/radjivcarrere/Downloads/normalizr-master/.babelrc.js")
    at /Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/radjivcarrere/Downloads/normalizr-master/examples/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! normalizr-redux-example@0.0.0 start: `babel-node ./`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the normalizr-redux-example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Any idea why how can I fix it?

**Comment by ralphstodomingo** [comment]
@radjivF Try running this: `npm install --save-dev babel-plugin-transform-object-rest-spread` as the redux example is missing this from its dev dependencies.

**Comment by paularmstrong** [comment]
You need to run `npm install` from the root directory first.
