### ISSUE TITLE
Project in examples/redux does not run

### ISSUE THREAD

**Issue by daffodil11** [paularmstrong/normalizr#427]
# Problem

When following the instructions in the README in the redux example project, a crash occurs.

**Input**

Here's how I'm using normalizr:
clone this repo
run yarn in the root dir
run yarn in the examples/redux dir
run yarn start

**Output**

Here's what I expect to see when I run the above:
An inquirer prompt.

Here's what I _actually_ see when I run the above:
```
> normalizr-redux-example@0.0.0 start /home/daffodil11/in-part-dev/normalizr/examples/redux
> babel-node ./

/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: /home/daffodil11/in-part-dev/normalizr/src/index.js: Unexpected token (69:71)
  67 |   if (!cache[schema.key][id]) {
  68 |     // Ensure we don't mutate it non-immutable objects
> 69 |     const entityCopy = ImmutableUtils.isImmutable(entity) ? entity : { ...entity };
     |                                                                        ^
  70 | 
  71 |     // Need to set this first so that if it is referenced further within the
  72 |     // denormalization the reference will already exist.
    at Parser.pp$5.raise (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp.unexpected (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:1627:8)
    at Parser.pp$3.parseIdentifier (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:4122:10)
    at Parser.pp$3.parsePropertyName (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:3945:103)
    at Parser.pp$3.parseObj (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:3862:12)
    at Parser.pp$3.parseExprAtom (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:3555:19)
    at Parser.pp$3.parseExprSubscripts (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/home/daffodil11/in-part-dev/normalizr/examples/redux/node_modules/babylon/lib/index.js:3218:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! normalizr-redux-example@0.0.0 start: `babel-node ./`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the normalizr-redux-example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Context**
Tested on:
openSUSE Tumbleweed, Node 10.16.3, yarn 1.19.1
MacOS High Sierra, node: v10.16.3 , yarn: 1.19.1

**Comment by barbaracassani** [comment]
I am having the same issue. Any quick fix available?

**Comment by nadavelyashiv** [comment]
same here, did someone managed handling this?
